name: Fetch YouTube Videos

on:
  schedule:
    - cron: '1 0 * * *'  # Runs at 12:01 AM UTC daily
  workflow_dispatch:     # Also allows manual trigger

jobs:
  fetch-videos:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add explicit permission
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true  # Ensure proper credentials
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install axios
        
      - name: Fetch YouTube videos
        run: node .github/scripts/fetch-videos.js
        env:
           REACT_APP_YOUTUBE_API_KEY: ${{ secrets.REACT_APP_YOUTUBE_API_KEY}}
          
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update YouTube videos
          file_pattern: public/youtube-videos.json
